name: Atom Package

on:
  create:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v1
        with:
          ref: ${{ steps.get_tag_name.outputs.TAG_NAME }}
      - uses: actions/checkout@v2
      - uses: UziTech/action-setup-atom@v1
        with:
          channel: stable
      - run: apm publish -t ${{steps.get_tag_name.outputs.TAG_NAME}}
        env:
          ATOM_ACCESS_TOKEN: ${{secrets.atom_access_token}}
